### PR TITLE
Add mtu verification for nics that are not sriov

### PR DESCRIPTION
**Pull request by SchSeba**
Signed-off-by: Sebastian Sch <sebassch@gmail.com>

### CODE REVIEW

**Comment by SchSeba** [comment]
example error message:

```
Warning  FailedCreatePodSandBox  8s    kubelet  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_testpod-1_tuning-testing_92b052e7-4f4f-4224-b8d0-3935153b697f_0(0d28b2d51106a034ae6bbef34109973068b342a464bfb3ac110c62cc99ee793f): error adding pod tuning-testing_testpod-1 to CNI network "multus-cni-network": plugin type="multus" name="multus-cni-network" failed (add): [tuning-testing/testpod-1/92b052e7-4f4f-4224-b8d0-3935153b697f:bond-nad1]: error adding container to network "bond-nad1": Invalid MTU (1500). The requested MTU for bond is bigger than that of the slave link (net1), slave mtu (1460)
```

**Comment by cgoncalves** [comment]
LGTM

**Comment by cgoncalves** [comment]
@mmirecki please review.

**Comment by mmirecki** [comment]
@Eoghan1232 @eoghanlawless could you please take a look?

**Review by eoghanlawless — COMMENTED** [review]
LGTM

**Comment by mmirecki** [comment]
@Eoghan1232 @eoghanlawless Could we merge this one please?

**Pull request merged**
